#pragma once

#include "SDL3/SDL_gamepad.h"

// Buttons
#define TE_GPBTN_A					SDL_GAMEPAD_BUTTON_SOUTH
#define TE_GPBTN_B					SDL_GAMEPAD_BUTTON_EAST
#define TE_GPBTN_X					SDL_GAMEPAD_BUTTON_WEST
#define TE_GPBTN_Y					SDL_GAMEPAD_BUTTON_NORTH

#define TE_GPBTN_BACK				SDL_GAMEPAD_BUTTON_BACK
#define TE_GPBTN_GUIDE				SDL_GAMEPAD_BUTTON_GUIDE
#define TE_GPBTN_START				SDL_GAMEPAD_BUTTON_START

#define TE_GPBTN_LEFTSTICK			SDL_GAMEPAD_BUTTON_LEFT_STICK
#define TE_GPBTN_RIGHTSTICK			SDL_GAMEPAD_BUTTON_RIGHT_STICK
#define TE_GPBTN_LEFTSHOULDER		SDL_GAMEPAD_BUTTON_LEFT_SHOULDER
#define TE_GPBTN_RIGHTSHOULDER		SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER

#define TE_GPBTN_DPAD_UP			SDL_GAMEPAD_BUTTON_DPAD_UP
#define TE_GPBTN_DPAD_DOWN			SDL_GAMEPAD_BUTTON_DPAD_DOWN
#define TE_GPBTN_DPAD_LEFT			SDL_GAMEPAD_BUTTON_DPAD_LEFT
#define TE_GPBTN_DPAD_RIGHT			SDL_GAMEPAD_BUTTON_DPAD_RIGHT

// Paddles and Misc buttons
#define TE_GPBTN_MISC1				SDL_GAMEPAD_BUTTON_MISC1
#define TE_GPBTN_PADDLE1			SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1
#define TE_GPBTN_PADDLE2			SDL_GAMEPAD_BUTTON_LEFT_PADDLE1
#define TE_GPBTN_PADDLE3			SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2
#define TE_GPBTN_PADDLE4			SDL_GAMEPAD_BUTTON_LEFT_PADDLE2
#define TE_GPBTN_MISC2				SDL_GAMEPAD_BUTTON_MISC2
#define TE_GPBTN_MISC3				SDL_GAMEPAD_BUTTON_MISC3
#define TE_GPBTN_MISC4				SDL_GAMEPAD_BUTTON_MISC4
#define TE_GPBTN_MISC5				SDL_GAMEPAD_BUTTON_MISC5
#define TE_GPBTN_MISC6				SDL_GAMEPAD_BUTTON_MISC6

// Axes
#define TE_GPAX_LEFTX				SDL_GAMEPAD_AXIS_LEFTX
#define TE_GPAX_LEFTY				SDL_GAMEPAD_AXIS_LEFTY
#define TE_GPAX_RIGHTX				SDL_GAMEPAD_AXIS_RIGHTX
#define TE_GPAX_RIGHTY				SDL_GAMEPAD_AXIS_RIGHTY
#define TE_GPAX_TRIGGERLEFT			SDL_GAMEPAD_AXIS_LEFT_TRIGGER
#define TE_GPAX_TRIGGERRIGHT		SDL_GAMEPAD_AXIS_RIGHT_TRIGGER