#pragma once

#include "SDL3/SDL_scancode.h"

// Alphabet
#define TE_SC_A					SDL_SCANCODE_A
#define TE_SC_B					SDL_SCANCODE_B
#define TE_SC_C					SDL_SCANCODE_C
#define TE_SC_D 				SDL_SCANCODE_D
#define TE_SC_E 				SDL_SCANCODE_E
#define TE_SC_F 				SDL_SCANCODE_F
#define TE_SC_G 				SDL_SCANCODE_G
#define TE_SC_H 				SDL_SCANCODE_H
#define TE_SC_I 				SDL_SCANCODE_I
#define TE_SC_J 				SDL_SCANCODE_J
#define TE_SC_K 				SDL_SCANCODE_K
#define TE_SC_L 				SDL_SCANCODE_L
#define TE_SC_M 				SDL_SCANCODE_M
#define TE_SC_N 				SDL_SCANCODE_N
#define TE_SC_O 				SDL_SCANCODE_O
#define TE_SC_P 				SDL_SCANCODE_P
#define TE_SC_Q 				SDL_SCANCODE_Q
#define TE_SC_R 				SDL_SCANCODE_R
#define TE_SC_S 				SDL_SCANCODE_S
#define TE_SC_T 				SDL_SCANCODE_T
#define TE_SC_U 				SDL_SCANCODE_U
#define TE_SC_V 				SDL_SCANCODE_V
#define TE_SC_W 				SDL_SCANCODE_W
#define TE_SC_X 				SDL_SCANCODE_X
#define TE_SC_Y 				SDL_SCANCODE_Y
#define TE_SC_Z 				SDL_SCANCODE_Z

// Numbers
#define TE_SC_0 				SDL_SCANCODE_0
#define TE_SC_1 				SDL_SCANCODE_1
#define TE_SC_2 				SDL_SCANCODE_2
#define TE_SC_3 				SDL_SCANCODE_3
#define TE_SC_4 				SDL_SCANCODE_4
#define TE_SC_5 				SDL_SCANCODE_5
#define TE_SC_6 				SDL_SCANCODE_6
#define TE_SC_7 				SDL_SCANCODE_7
#define TE_SC_8 				SDL_SCANCODE_8
#define TE_SC_9 				SDL_SCANCODE_9

// Space and control keys
#define TE_SC_SPACE				SDL_SCANCODE_SPACE
#define TE_SC_RETURN			SDL_SCANCODE_RETURN
#define TE_SC_ESCAPE			SDL_SCANCODE_ESCAPE
#define TE_SC_BACKSPACE			SDL_SCANCODE_BACKSPACE
#define TE_SC_TAB				SDL_SCANCODE_TAB
#define TE_SC_CAPSLOCK			SDL_SCANCODE_CAPSLOCK
#define TE_SC_LSHIFT			SDL_SCANCODE_LSHIFT
#define TE_SC_RSHIFT			SDL_SCANCODE_RSHIFT
#define TE_SC_LCTRL				SDL_SCANCODE_LCTRL
#define TE_SC_RCTRL				SDL_SCANCODE_RCTRL
#define TE_SC_LALT				SDL_SCANCODE_LALT
#define TE_SC_RALT				SDL_SCANCODE_RALT
#define TE_SC_LGUI				SDL_SCANCODE_LGUI
#define TE_SC_RGUI				SDL_SCANCODE_RGUI
#define TE_SC_MENU				SDL_SCANCODE_APPLICATION
#define TE_SC_NUMLOCK			SDL_SCANCODE_NUMLOCKCLEAR
#define TE_SC_PRINTSCREEN		SDL_SCANCODE_PRINTSCREEN

// Function keys
#define TE_SC_F1 				SDL_SCANCODE_F1
#define TE_SC_F2 				SDL_SCANCODE_F2
#define TE_SC_F3 				SDL_SCANCODE_F3
#define TE_SC_F4 				SDL_SCANCODE_F4
#define TE_SC_F5 				SDL_SCANCODE_F5
#define TE_SC_F6 				SDL_SCANCODE_F6
#define TE_SC_F7 				SDL_SCANCODE_F7
#define TE_SC_F8 				SDL_SCANCODE_F8
#define TE_SC_F9 				SDL_SCANCODE_F9
#define TE_SC_F10 				SDL_SCANCODE_F10
#define TE_SC_F11 				SDL_SCANCODE_F11
#define TE_SC_F12 				SDL_SCANCODE_F12
#define TE_SC_F13 				SDL_SCANCODE_F13
#define TE_SC_F14 				SDL_SCANCODE_F14
#define TE_SC_F15 				SDL_SCANCODE_F15
#define TE_SC_F16 				SDL_SCANCODE_F16
#define TE_SC_F17 				SDL_SCANCODE_F17
#define TE_SC_F18 				SDL_SCANCODE_F18
#define TE_SC_F19 				SDL_SCANCODE_F19
#define TE_SC_F20 				SDL_SCANCODE_F20
#define TE_SC_F21 				SDL_SCANCODE_F21
#define TE_SC_F22 				SDL_SCANCODE_F22
#define TE_SC_F23 				SDL_SCANCODE_F23
#define TE_SC_F24 				SDL_SCANCODE_F24

// Arrow keys
#define TE_SC_UP				SDL_SCANCODE_UP
#define TE_SC_DOWN 				SDL_SCANCODE_DOWN
#define TE_SC_LEFT 				SDL_SCANCODE_LEFT
#define TE_SC_RIGHT				SDL_SCANCODE_RIGHT
#define TE_SC_PAGEUP			SDL_SCANCODE_PAGEUP
#define TE_SC_PAGEDOWN			SDL_SCANCODE_PAGEDOWN
#define TE_SC_HOME				SDL_SCANCODE_HOME
#define TE_SC_END 				SDL_SCANCODE_END
#define TE_SC_INSERT			SDL_SCANCODE_INSERT
#define TE_SC_DELETE			SDL_SCANCODE_DELETE

// Punctuation
#define TE_SC_MINUS				SDL_SCANCODE_MINUS
#define TE_SC_EQUALS			SDL_SCANCODE_EQUALS
#define TE_SC_LEFTBRACKET		SDL_SCANCODE_LEFTBRACKET
#define TE_SC_RIGHTBRACKET		SDL_SCANCODE_RIGHTBRACKET
#define TE_SC_BACKSLASH			SDL_SCANCODE_BACKSLASH
#define TE_SC_SEMICOLON			SDL_SCANCODE_SEMICOLON
#define TE_SC_APOSTROPHE		SDL_SCANCODE_APOSTROPHE
#define TE_SC_GRAVE				SDL_SCANCODE_GRAVE
#define TE_SC_COMMA				SDL_SCANCODE_COMMA
#define TE_SC_PERIOD			SDL_SCANCODE_PERIOD
#define TE_SC_SLASH				SDL_SCANCODE_SLASH

// Numpad keys
#define TE_SC_KP_0				SDL_SCANCODE_KP_0
#define TE_SC_KP_1				SDL_SCANCODE_KP_1
#define TE_SC_KP_2				SDL_SCANCODE_KP_2
#define TE_SC_KP_3				SDL_SCANCODE_KP_3
#define TE_SC_KP_4				SDL_SCANCODE_KP_4
#define TE_SC_KP_5				SDL_SCANCODE_KP_5
#define TE_SC_KP_6				SDL_SCANCODE_KP_6
#define TE_SC_KP_7				SDL_SCANCODE_KP_7
#define TE_SC_KP_8				SDL_SCANCODE_KP_8
#define TE_SC_KP_9				SDL_SCANCODE_KP_9
#define TE_SC_KP_DECIMAL		SDL_SCANCODE_KP_PERIOD
#define TE_SC_KP_DIVIDE			SDL_SCANCODE_KP_DIVIDE
#define TE_SC_KP_MULTIPLY		SDL_SCANCODE_KP_MULTIPLY
#define TE_SC_KP_MINUS			SDL_SCANCODE_KP_MINUS
#define TE_SC_KP_PLUS			SDL_SCANCODE_KP_PLUS
#define TE_SC_KP_ENTER			SDL_SCANCODE_KP_ENTER
#define TE_SC_KP_EQUALS			SDL_SCANCODE_KP_EQUALS